// <auto-generated />
using System;
using Main.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Manuscripta.Main.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20260301232324_RenameExternalDeviceIdToDeviceId")]
    partial class RenameExternalDeviceIdToDeviceId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Main.Models.Entities.AttachmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileBaseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("Main.Models.Entities.ConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AiScaffoldingEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeedbackStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MascotSelection")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SummarisationEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TextSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TtsEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("Main.Models.Entities.EmailCredentialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpHost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EmailCredentials");
                });

            modelBuilder.Entity("Main.Models.Entities.ExternalDeviceEntity", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationData")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceId");

                    b.ToTable("ExternalDevices");
                });

            modelBuilder.Entity("Main.Models.Entities.LessonEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("Main.Models.Entities.MaterialDataEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ActualAge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReadingAge")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("MaterialType");

                    b.HasIndex("Timestamp");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("Main.Models.Entities.QuestionDataEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectAnswer")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MarkScheme")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxScore")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Options")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("QuestionType");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Main.Models.Entities.SourceDocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Transcript")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UnitCollectionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UnitCollectionId");

                    b.ToTable("SourceDocuments");
                });

            modelBuilder.Entity("Main.Models.Entities.UnitCollectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UnitCollections");
                });

            modelBuilder.Entity("Main.Models.Entities.UnitEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("SourceDocuments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UnitCollectionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UnitCollectionId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Main.Models.Entities.AttachmentEntity", b =>
                {
                    b.HasOne("Main.Models.Entities.MaterialDataEntity", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Main.Models.Entities.LessonEntity", b =>
                {
                    b.HasOne("Main.Models.Entities.UnitEntity", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Main.Models.Entities.MaterialDataEntity", b =>
                {
                    b.HasOne("Main.Models.Entities.LessonEntity", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Main.Models.Entities.QuestionDataEntity", b =>
                {
                    b.HasOne("Main.Models.Entities.MaterialDataEntity", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Main.Models.Entities.SourceDocumentEntity", b =>
                {
                    b.HasOne("Main.Models.Entities.UnitCollectionEntity", "UnitCollection")
                        .WithMany()
                        .HasForeignKey("UnitCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnitCollection");
                });

            modelBuilder.Entity("Main.Models.Entities.UnitEntity", b =>
                {
                    b.HasOne("Main.Models.Entities.UnitCollectionEntity", "UnitCollection")
                        .WithMany()
                        .HasForeignKey("UnitCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnitCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
