import { app, BrowserWindow, session, ipcMain, dialog, protocol, net } from 'electron';
import * as fsSync from 'fs';
import * as pathModule from 'path';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// Get attachments directory path
function getAttachmentsDir(): string {
  const appDataPath = app.getPath('appData');
  return pathModule.join(appDataPath, 'ManuscriptaTeacherApp', 'Attachments');
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // Set Content Security Policy to allow Google Fonts, Tailwind CDN, and PDF worker
  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    callback({
      responseHeaders: {
        ...details.responseHeaders,
        'Content-Security-Policy': [
          "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob:; " +
          "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.tailwindcss.com https://unpkg.com; " +
          "worker-src 'self' blob: https://unpkg.com; " +
          "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; " +
          "style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com; " +
          "font-src 'self' https://fonts.gstatic.com data:; " +
          "img-src 'self' data: blob:; " +
          "connect-src 'self' http://localhost:5910 ws://localhost:5910 https://fonts.googleapis.com https://fonts.gstatic.com https://unpkg.com;"
        ]
      }
    });
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools (if needed)
  // mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// ==========================================
// IPC Handlers for Attachment File Operations
// Per FrontendWorkflowSpecifications §4C(4)
// ==========================================

// Ensure attachments directory exists
function ensureAttachmentsDir(): void {
  const dir = getAttachmentsDir();
  if (!fsSync.existsSync(dir)) {
    fsSync.mkdirSync(dir, { recursive: true });
  }
}

// Initialize attachments directory on app ready
app.whenReady().then(() => {
  ensureAttachmentsDir();
});

// Show open dialog for file picker
ipcMain.handle('show-open-dialog', async (_event, options: Electron.OpenDialogOptions) => {
  const result = await dialog.showOpenDialog(options);
  return result;
});

// Save attachment file - copy to attachments directory with UUID filename
ipcMain.handle('save-attachment-file', async (_event, sourcePath: string, uuid: string, extension: string) => {
  ensureAttachmentsDir();
  const destPath = pathModule.join(getAttachmentsDir(), `${uuid}.${extension}`);
  fsSync.copyFileSync(sourcePath, destPath);
  return destPath;
});

// Get attachment file path
ipcMain.handle('get-attachment-path', (_event, uuid: string, extension: string) => {
  return pathModule.join(getAttachmentsDir(), `${uuid}.${extension}`);
});

// Get attachment as data URL for WYSIWYG display
ipcMain.handle('get-attachment-data-url', async (_event, uuid: string, extension: string) => {
  const filePath = pathModule.join(getAttachmentsDir(), `${uuid}.${extension}`);
  if (!fsSync.existsSync(filePath)) {
    return null;
  }
  const data = fsSync.readFileSync(filePath);
  const base64 = data.toString('base64');
  const mimeType = extension === 'pdf' ? 'application/pdf' : `image/${extension}`;
  return `data:${mimeType};base64,${base64}`;
});

// Delete attachment file
ipcMain.handle('delete-attachment-file', async (_event, uuid: string, extension: string) => {
  const filePath = pathModule.join(getAttachmentsDir(), `${uuid}.${extension}`);
  if (fsSync.existsSync(filePath)) {
    fsSync.unlinkSync(filePath);
  }
  return true;
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
