import { app, BrowserWindow, session, ipcMain, dialog } from 'electron';
import * as fsSync from 'fs';
import * as pathModule from 'path';
import { backendProcessManager, BackendState } from './BackendProcessManager';
import { BACKEND_URL, BACKEND_WS_URL } from './config';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// References to windows
let splashWindow: BrowserWindow | null = null;
let mainWindow: BrowserWindow | null = null;

// Get attachments directory path
function getAttachmentsDir(): string {
  const appDataPath = app.getPath('appData');
  return pathModule.join(appDataPath, 'ManuscriptaTeacherApp', 'Attachments');
}

/**
 * Creates the splash screen window.
 * Per FrontendWorkflowSpecifications §2ZA(4).
 */
const createSplashWindow = (): void => {
  splashWindow = new BrowserWindow({
    width: 500,
    height: 400,
    frame: false,
    transparent: false,
    resizable: false,
    center: true,
    show: false,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  // Load splash HTML
  const splashPath = pathModule.join(__dirname, 'splash.html');
  if (fsSync.existsSync(splashPath)) {
    splashWindow.loadFile(splashPath);
  } else {
    // Fallback for webpack bundled scenario
    splashWindow.loadURL(`data:text/html,
      <html>
        <head>
          <style>
            body { 
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
              background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
              height: 100vh; display: flex; justify-content: center; align-items: center;
              color: white; margin: 0;
            }
            .container { text-align: center; }
            .spinner { width: 40px; height: 40px; border: 3px solid rgba(255,255,255,0.3);
              border-top-color: white; border-radius: 50%; animation: spin 1s linear infinite;
              margin: 20px auto; }
            @keyframes spin { to { transform: rotate(360deg); } }
          </style>
        </head>
        <body>
          <div class="container">
            <h1>📚 Manuscripta</h1>
            <div class="spinner"></div>
            <p>Starting application...</p>
          </div>
        </body>
      </html>
    `);
  }

  splashWindow.once('ready-to-show', () => {
    splashWindow?.show();
  });
};

/**
 * Creates the main application window.
 * Per FrontendWorkflowSpecifications §2ZA(5)(c)(ii).
 */
const createMainWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    show: false, // Don't show until ready
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // Set Content Security Policy to allow Google Fonts, Tailwind CDN, and PDF worker
  // Per FrontendWorkflowSpecifications §2ZA(8)(a)(ii): Use centralized port config
  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    callback({
      responseHeaders: {
        ...details.responseHeaders,
        'Content-Security-Policy': [
          "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob:; " +
          "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.tailwindcss.com https://unpkg.com; " +
          "worker-src 'self' blob: https://unpkg.com; " +
          "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; " +
          "style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com; " +
          "font-src 'self' https://fonts.gstatic.com data:; " +
          "img-src 'self' data: blob:; " +
          `connect-src 'self' ${BACKEND_URL} ${BACKEND_WS_URL} https://fonts.googleapis.com https://fonts.gstatic.com https://unpkg.com https: http: blob:;`
        ]
      }
    });
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Show main window when ready, close splash
  mainWindow.once('ready-to-show', () => {
    // Per §2ZA(5)(c)(i): Dismiss splash screen
    if (splashWindow) {
      splashWindow.close();
      splashWindow = null;
    }
    mainWindow?.show();
  });

  mainWindow.on('closed', () => {
    mainWindow = null;
  });

  // Open the DevTools (if needed)
  // mainWindow.webContents.openDevTools();
};

/**
 * Initializes the application with backend lifecycle management.
 * Per FrontendWorkflowSpecifications §2ZA.
 */
const initializeApp = async (): Promise<void> => {
  // Per §2ZA(4)(a): Display splash screen before backend is ready
  createSplashWindow();

  // Set up backend process manager callbacks
  backendProcessManager.onReady(() => {
    if (!mainWindow || mainWindow.isDestroyed()) {
      console.log('Backend is ready, creating main window');
      // Per §2ZA(5)(c)(ii): Create main window and establish SignalR connection
      createMainWindow();
    } else {
      console.log('Backend is ready, main window already exists; skipping creation');
    }
  });

  backendProcessManager.onError((error) => {
    console.error('Backend error:', error);
    // Per §2ZA(5)(d): Display error message
    if (splashWindow) {
      dialog.showErrorBox(
        'Application Startup Error',
        `${error}\n\nPlease try restarting the application.`
      );
      app.quit();
    }
  });

  backendProcessManager.onStateChange((state) => {
    console.log(`Backend state changed to: ${state}`);
    
    // Per §2ZA(6)(c)(i): Display reconnecting indicator
    if (state === BackendState.RESTARTING && mainWindow) {
      mainWindow.webContents.send('backend-state-change', 'reconnecting');
    } else if (state === BackendState.RUNNING && mainWindow) {
      mainWindow.webContents.send('backend-state-change', 'connected');
    } else if (state === BackendState.FAILED && mainWindow) {
      // Per §2ZA(4)(d): Avoid wording that implies frontend-backend separation
      dialog.showErrorBox(
        'Application Error',
        'The application encountered a problem and could not recover. Please restart the application.'
      );
    }
  });

  // Per §2ZA(3): Start the backend process
  try {
    await backendProcessManager.start();
  } catch (err) {
    console.error('Failed to start backend:', err);
    // Per §2ZA(5)(d)(i): Display error message
    dialog.showErrorBox(
      'Application Startup Error',
      'Failed to start the application backend. Please ensure the application is installed correctly and try again.'
    );
    app.quit();
  }
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  ensureAttachmentsDir();
  initializeApp();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

// Per FrontendWorkflowSpecifications §2ZA(7): Graceful shutdown
let isGracefulQuitInProgress = false;

function handleWillQuit(event: Electron.Event) {
  // Only intercept the first quit attempt; subsequent attempts proceed normally.
  if (isGracefulQuitInProgress) {
    return;
  }

  isGracefulQuitInProgress = true;
  event.preventDefault();

  (async () => {
    try {
      // Per §2ZA(7)(a): Stop the backend process gracefully
      await backendProcessManager.stop();
    } catch (err) {
      console.error('Error stopping backend:', err);
    } finally {
      // After graceful shutdown, allow Electron's normal quit flow to proceed
      app.removeListener('will-quit', handleWillQuit);
      app.quit();
    }
  })();
}

app.on('will-quit', handleWillQuit);
app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0 && backendProcessManager.getState() === BackendState.RUNNING) {
    createMainWindow();
  }
});

// ==========================================
// IPC Handlers for Attachment File Operations
// Per FrontendWorkflowSpecifications §4C(4)
// ==========================================

// Ensure attachments directory exists
function ensureAttachmentsDir(): void {
  const dir = getAttachmentsDir();
  if (!fsSync.existsSync(dir)) {
    fsSync.mkdirSync(dir, { recursive: true });
  }
}

// Show open dialog for file picker
ipcMain.handle('show-open-dialog', async (_event, options: Electron.OpenDialogOptions) => {
  const result = await dialog.showOpenDialog(options);
  return result;
});

// Save attachment file - copy to attachments directory with UUID filename
ipcMain.handle('save-attachment-file', async (_event, sourcePath: string, uuid: string, extension: string) => {
  ensureAttachmentsDir();
  const destPath = pathModule.join(getAttachmentsDir(), `${uuid}.${extension}`);
  fsSync.copyFileSync(sourcePath, destPath);
  return destPath;
});

// Get attachment file path
ipcMain.handle('get-attachment-path', (_event, uuid: string, extension: string) => {
  return pathModule.join(getAttachmentsDir(), `${uuid}.${extension}`);
});

// Get attachment as data URL for WYSIWYG display
ipcMain.handle('get-attachment-data-url', async (_event, uuid: string, extension: string) => {
  const filePath = pathModule.join(getAttachmentsDir(), `${uuid}.${extension}`);
  if (!fsSync.existsSync(filePath)) {
    return null;
  }
  const data = fsSync.readFileSync(filePath);
  const base64 = data.toString('base64');
  const mimeType = extension === 'pdf' ? 'application/pdf' : `image/${extension}`;
  return `data:${mimeType};base64,${base64}`;
});

// Delete attachment file
ipcMain.handle('delete-attachment-file', async (_event, uuid: string, extension: string) => {
  const filePath = pathModule.join(getAttachmentsDir(), `${uuid}.${extension}`);
  if (fsSync.existsSync(filePath)) {
    fsSync.unlinkSync(filePath);
  }
  return true;
});

// Save attachment from base64 data (for clipboard paste per §4C(4)(d)(ii))
ipcMain.handle('save-attachment-from-base64', async (_event, base64Data: string, uuid: string, extension: string) => {
  ensureAttachmentsDir();
  const destPath = pathModule.join(getAttachmentsDir(), `${uuid}.${extension}`);
  const buffer = Buffer.from(base64Data, 'base64');
  fsSync.writeFileSync(destPath, buffer);
  return destPath;
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
