using System.ComponentModel.DataAnnotations;
using Main.Models.Enums;

namespace Main.Models.Entities.Sessions;

/// <summary>
/// Polymorphic entity for sessions.
/// Represents a student's session working on a specific material.
/// Validation rules defined in Validation Rules §2D.
/// </summary>
public class SessionEntity
{
    /// <summary>
    /// Unique identifier for the session (generated by Android client per §3(2)).
    /// </summary>
    [Key]
    [Required]
    public Guid Id { get; set; }

    /// <summary>
    /// References the material the student should work on during the lesson.
    /// §2D(1)(a)
    /// </summary>
    [Required]
    public Guid MaterialId { get; set; }

    /// <summary>
    /// Start timestamp of the session.
    /// §2D(1)(b)
    /// </summary>
    [Required]
    public DateTime StartTime { get; set; }

    /// <summary>
    /// Session status indicating current state.
    /// §2D(1)(c)
    /// </summary>
    [Required]
    public SessionStatus SessionStatus { get; set; }

    /// <summary>
    /// The device ID the session is related to.
    /// §2D(1)(d)
    /// </summary>
    [Required]
    public Guid DeviceId { get; set; }

    /// <summary>
    /// End timestamp, for non-active sessions.
    /// §2D(2)(a) - Optional, but required when SessionStatus is PAUSED, COMPLETED, or CANCELLED per §2D(3)(a).
    /// </summary>
    public DateTime? EndTime { get; set; }

    /// <summary>
    /// Private parameterless constructor for EF Core and deserialization.
    /// </summary>
    public SessionEntity() { }

    /// <summary>
    /// Creates a new SessionEntity.
    /// </summary>
    /// <param name="id">Unique session ID (generated by Android client).</param>
    /// <param name="materialId">The material this session is associated with.</param>
    /// <param name="startTime">Timestamp of session start.</param>
    /// <param name="sessionStatus">Current session status.</param>
    /// <param name="deviceId">The device ID this session belongs to.</param>
    /// <param name="endTime">Optional end time (required for non-ACTIVE sessions).</param>
    public SessionEntity(
        Guid id,
        Guid materialId,
        DateTime startTime,
        SessionStatus sessionStatus,
        Guid deviceId,
        DateTime? endTime = null)
    {
        Id = id;
        MaterialId = materialId;
        StartTime = startTime;
        SessionStatus = sessionStatus;
        DeviceId = deviceId;
        EndTime = endTime;
    }
}
