export interface Theme {
  name: string;
  colors: {
    '--color-brand-cream': string;
    '--color-brand-orange': string;
    '--color-brand-orange-light': string;
    '--color-brand-orange-dark': string;
    '--color-brand-yellow': string;
    '--color-brand-blue': string;
    '--color-brand-green': string;
    '--color-brand-gray': string;
    '--color-text-heading': string;
    '--color-text-body': string;
    '--color-text-on-yellow': string;
    '--color-text-on-blue': string;
  };
}

export const themes: Record<string, Theme> = {
  default: {
    name: 'Default',
    colors: {
      '--color-brand-cream': '#F8F7F5',
      '--color-brand-orange': '#FF6106',
      '--color-brand-orange-light': '#FEE3DA',
      '--color-brand-orange-dark': '#E55605',
      '--color-brand-yellow': '#FFE782',
      '--color-brand-blue': '#ABD8F9',
      '--color-brand-green': '#15502E',
      '--color-brand-gray': '#F3F3F3',
      '--color-text-heading': '#212631',
      '--color-text-body': '#14201E',
      '--color-text-on-yellow': '#5C4A00',
      '--color-text-on-blue': '#1A3A5C',
    },
  },
  boldPrimary: {
    name: 'Bold Primary & Dark',
    colors: {
      '--color-brand-cream': '#FAFAFA',
      '--color-brand-orange': '#E01A4F',
      '--color-brand-orange-light': '#F15946',
      '--color-brand-orange-dark': '#0C090D',
      '--color-brand-yellow': '#F9C22E',
      '--color-brand-blue': '#53B3CB',
      '--color-brand-green': '#0C090D',
      '--color-brand-gray': '#F3F3F3',
      '--color-text-heading': '#0C090D',
      '--color-text-body': '#0C090D',
      '--color-text-on-yellow': '#4A3800',
      '--color-text-on-blue': '#0C090D',
    },
  },
  earthyGeometric: {
    name: 'Earthy & Geometric',
    colors: {
      '--color-brand-cream': '#E6E6E6',
      '--color-brand-orange': '#FF8552',
      '--color-brand-orange-light': '#FFB896',
      '--color-brand-orange-dark': '#297373',
      '--color-brand-yellow': '#E9D758',
      '--color-brand-blue': '#297373',
      '--color-brand-green': '#39393A',
      '--color-brand-gray': '#E6E6E6',
      '--color-text-heading': '#39393A',
      '--color-text-body': '#39393A',
      '--color-text-on-yellow': '#3A3400',
      '--color-text-on-blue': '#FFFFFF',
    },
  },
  navyGold: {
    name: 'Navy & Gold Contrast',
    colors: {
      '--color-brand-cream': '#F6D8AE',
      '--color-brand-orange': '#DA4167',
      '--color-brand-orange-light': '#F6D8AE',
      '--color-brand-orange-dark': '#2E4057',
      '--color-brand-yellow': '#F4D35E',
      '--color-brand-blue': '#083D77',
      '--color-brand-green': '#2E4057',
      '--color-brand-gray': '#F6D8AE',
      '--color-text-heading': '#2E4057',
      '--color-text-body': '#2E4057',
      '--color-text-on-yellow': '#3A3000',
      '--color-text-on-blue': '#FFFFFF',
    },
  },
  mutedGreens: {
    name: 'Muted Greens & Browns',
    colors: {
      '--color-brand-cream': '#F2E3BC',
      '--color-brand-orange': '#618985',
      '--color-brand-orange-light': '#96BBBB',
      '--color-brand-orange-dark': '#414535',
      '--color-brand-yellow': '#C19875',
      '--color-brand-blue': '#96BBBB',
      '--color-brand-green': '#414535',
      '--color-brand-gray': '#F2E3BC',
      '--color-text-heading': '#414535',
      '--color-text-body': '#414535',
      '--color-text-on-yellow': '#2D2518',
      '--color-text-on-blue': '#2D3830',
    },
  },
  deepBluePink: {
    name: 'Deep Blue & Soft Pink',
    colors: {
      '--color-brand-cream': '#F2F3D9',
      '--color-brand-orange': '#C16E70',
      '--color-brand-orange-light': '#DC9E82',
      '--color-brand-orange-dark': '#151E3F',
      '--color-brand-yellow': '#DC9E82',
      '--color-brand-blue': '#151E3F',
      '--color-brand-green': '#030027',
      '--color-brand-gray': '#F2F3D9',
      '--color-text-heading': '#151E3F',
      '--color-text-body': '#151E3F',
      '--color-text-on-yellow': '#3A2820',
      '--color-text-on-blue': '#FFFFFF',
    },
  },
  pastelPurple: {
    name: 'Pastel Purple & Yellow',
    colors: {
      '--color-brand-cream': '#FFFFFB',
      '--color-brand-orange': '#FF6B6C',
      '--color-brand-orange-light': '#FFC145',
      '--color-brand-orange-dark': '#5B5F97',
      '--color-brand-yellow': '#FFC145',
      '--color-brand-blue': '#B8B8D1',
      '--color-brand-green': '#5B5F97',
      '--color-brand-gray': '#FFFFFB',
      '--color-text-heading': '#5B5F97',
      '--color-text-body': '#5B5F97',
      '--color-text-on-yellow': '#4A3000',
      '--color-text-on-blue': '#2A2D4A',
    },
  },
  vintageReds: {
    name: 'Vintage Reds & Creams',
    colors: {
      '--color-brand-cream': '#F1F0CC',
      '--color-brand-orange': '#A71D31',
      '--color-brand-orange-light': '#D5BF86',
      '--color-brand-orange-dark': '#3F0D12',
      '--color-brand-yellow': '#D5BF86',
      '--color-brand-blue': '#8D775F',
      '--color-brand-green': '#3F0D12',
      '--color-brand-gray': '#F1F0CC',
      '--color-text-heading': '#3F0D12',
      '--color-text-body': '#3F0D12',
      '--color-text-on-yellow': '#3A2D1A',
      '--color-text-on-blue': '#FFFFFF',
    },
  },
  darkOxblood: {
    name: 'Dark Grey & Oxblood',
    colors: {
      '--color-brand-cream': '#FFF8F0',
      '--color-brand-orange': '#92140C',
      '--color-brand-orange-light': '#FFCF99',
      '--color-brand-orange-dark': '#111D4A',
      '--color-brand-yellow': '#FFCF99',
      '--color-brand-blue': '#111D4A',
      '--color-brand-green': '#1E1E24',
      '--color-brand-gray': '#FFF8F0',
      '--color-text-heading': '#1E1E24',
      '--color-text-body': '#1E1E24',
      '--color-text-on-yellow': '#4A3000',
      '--color-text-on-blue': '#FFFFFF',
    },
  },
  patriotic: {
    name: 'Patriotic Tones',
    colors: {
      '--color-brand-cream': '#FBFEF9',
      '--color-brand-orange': '#A63446',
      '--color-brand-orange-light': '#E8A0AB',
      '--color-brand-orange-dark': '#7E1946',
      '--color-brand-yellow': '#E8D6A8',
      '--color-brand-blue': '#0C6291',
      '--color-brand-green': '#000004',
      '--color-brand-gray': '#FBFEF9',
      '--color-text-heading': '#000004',
      '--color-text-body': '#000004',
      '--color-text-on-yellow': '#3A3000',
      '--color-text-on-blue': '#FFFFFF',
    },
  },
  vibrantSunset: {
    name: 'Vibrant Sunset',
    colors: {
      '--color-brand-cream': '#FFFECB',
      '--color-brand-orange': '#FF2E00',
      '--color-brand-orange-light': '#FEA82F',
      '--color-brand-orange-dark': '#423E3B',
      '--color-brand-yellow': '#FEA82F',
      '--color-brand-blue': '#5448C8',
      '--color-brand-green': '#423E3B',
      '--color-brand-gray': '#FFFECB',
      '--color-text-heading': '#423E3B',
      '--color-text-body': '#423E3B',
      '--color-text-on-yellow': '#4A3500',
      '--color-text-on-blue': '#FFFFFF',
    },
  },
  darkWine: {
    name: 'Dark Wine & Sandy Brown',
    colors: {
      '--color-brand-cream': '#E0E0E2',
      '--color-brand-orange': '#721817',
      '--color-brand-orange-light': '#FA9F42',
      '--color-brand-orange-dark': '#2B4162',
      '--color-brand-yellow': '#FA9F42',
      '--color-brand-blue': '#2B4162',
      '--color-brand-green': '#0B6E4F',
      '--color-brand-gray': '#E0E0E2',
      '--color-text-heading': '#2B4162',
      '--color-text-body': '#2B4162',
      '--color-text-on-yellow': '#4A3000',
      '--color-text-on-blue': '#FFFFFF',
    },
  },
  softPurples: {
    name: 'Soft Purples & Grey',
    colors: {
      '--color-brand-cream': '#CEBACF',
      '--color-brand-orange': '#7D80DA',
      '--color-brand-orange-light': '#B0A3D4',
      '--color-brand-orange-dark': '#65655E',
      '--color-brand-yellow': '#C6AFB1',
      '--color-brand-blue': '#B0A3D4',
      '--color-brand-green': '#65655E',
      '--color-brand-gray': '#CEBACF',
      '--color-text-heading': '#65655E',
      '--color-text-body': '#65655E',
      '--color-text-on-yellow': '#3A3035',
      '--color-text-on-blue': '#2A2845',
    },
  },
  peachGreens: {
    name: 'Peach & Muted Greens',
    colors: {
      '--color-brand-cream': '#FFCAB1',
      '--color-brand-orange': '#E05263',
      '--color-brand-orange-light': '#FFCAB1',
      '--color-brand-orange-dark': '#659157',
      '--color-brand-yellow': '#A1C084',
      '--color-brand-blue': '#69A2B0',
      '--color-brand-green': '#659157',
      '--color-brand-gray': '#FFCAB1',
      '--color-text-heading': '#659157',
      '--color-text-body': '#3A4A30',
      '--color-text-on-yellow': '#2A3A20',
      '--color-text-on-blue': '#1A3040',
    },
  },
  pastelLime: {
    name: 'Pastel Lime & Blue',
    colors: {
      '--color-brand-cream': '#FFFD98',
      '--color-brand-orange': '#7A9CC6',
      '--color-brand-orange-light': '#BDE4A7',
      '--color-brand-orange-dark': '#7A9CC6',
      '--color-brand-yellow': '#BDE4A7',
      '--color-brand-blue': '#9FBBCC',
      '--color-brand-green': '#B3D2B2',
      '--color-brand-gray': '#FFFD98',
      '--color-text-heading': '#3A4A5A',
      '--color-text-body': '#3A4A5A',
      '--color-text-on-yellow': '#2A4A20',
      '--color-text-on-blue': '#1A3050',
    },
  },
  earthyMint: {
    name: 'Earthy Browns & Mint',
    colors: {
      '--color-brand-cream': '#EAF4D3',
      '--color-brand-orange': '#994636',
      '--color-brand-orange-light': '#CA907E',
      '--color-brand-orange-dark': '#895B1E',
      '--color-brand-yellow': '#DBD8AE',
      '--color-brand-blue': '#CA907E',
      '--color-brand-green': '#895B1E',
      '--color-brand-gray': '#EAF4D3',
      '--color-text-heading': '#895B1E',
      '--color-text-body': '#4A3A20',
      '--color-text-on-yellow': '#3A3020',
      '--color-text-on-blue': '#3A2A20',
    },
  },
  vibrantPrimary: {
    name: 'Vibrant Primary Mix',
    colors: {
      '--color-brand-cream': '#FFFDF0',
      '--color-brand-orange': '#E55934',
      '--color-brand-orange-light': '#FA7921',
      '--color-brand-orange-dark': '#9BC53D',
      '--color-brand-yellow': '#FDE74C',
      '--color-brand-blue': '#5BC0EB',
      '--color-brand-green': '#9BC53D',
      '--color-brand-gray': '#FFFDF0',
      '--color-text-heading': '#2A3A20',
      '--color-text-body': '#2A3A20',
      '--color-text-on-yellow': '#4A4000',
      '--color-text-on-blue': '#0A3050',
    },
  },
  blueGreySunset: {
    name: 'Blue Grey & Sunset Tones',
    colors: {
      '--color-brand-cream': '#FFF8F0',
      '--color-brand-orange': '#FF3C38',
      '--color-brand-orange-light': '#FF8C42',
      '--color-brand-orange-dark': '#A23E48',
      '--color-brand-yellow': '#FFF275',
      '--color-brand-blue': '#6699CC',
      '--color-brand-green': '#A23E48',
      '--color-brand-gray': '#FFF8F0',
      '--color-text-heading': '#3A3040',
      '--color-text-body': '#3A3040',
      '--color-text-on-yellow': '#4A4000',
      '--color-text-on-blue': '#FFFFFF',
    },
  },
};
