package com.manuscripta.student.network.dto;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import com.manuscripta.student.domain.model.Response;

import org.junit.Test;

import java.util.Arrays;
import java.util.List;

/**
 * Unit tests for {@link ResponseDtoMapper}.
 * Tests mapping between Response domain model and ResponseDto for network transmission.
 */
public class ResponseDtoMapperTest {

    private static final String TEST_ID = "550e8400-e29b-41d4-a716-446655440000";
    private static final String TEST_QUESTION_ID = "q-uuid-123";
    private static final String TEST_MATERIAL_ID = "mat-uuid-456";
    private static final String TEST_DEVICE_ID = "device-uuid-789";
    private static final String TEST_ANSWER = "3";
    private static final long TEST_TIMESTAMP = 1698400200000L; // 2023-10-27T09:50:00Z

    @Test
    public void testToDto() {
        // Given
        Response domain = new Response(
                TEST_ID,
                TEST_QUESTION_ID,
                TEST_ANSWER,
                false,
                TEST_TIMESTAMP,
                false,
                TEST_DEVICE_ID
        );

        // When
        ResponseDto dto = ResponseDtoMapper.toDto(domain, TEST_MATERIAL_ID);

        // Then
        assertNotNull(dto);
        assertEquals(TEST_ID, dto.getId());
        assertEquals(TEST_QUESTION_ID, dto.getQuestionId());
        assertEquals(TEST_MATERIAL_ID, dto.getMaterialId());
        assertEquals(TEST_DEVICE_ID, dto.getStudentId());
        assertEquals(TEST_ANSWER, dto.getAnswer());
        assertNotNull(dto.getTimestamp());
        // isCorrect is false, so should be null (only set when true)
        assertNull(dto.getIsCorrect());
    }

    @Test
    public void testToDtoWithCorrectResponse() {
        // Given - response marked as correct
        Response domain = new Response(
                TEST_ID,
                TEST_QUESTION_ID,
                TEST_ANSWER,
                true,  // Correct response
                TEST_TIMESTAMP,
                false,
                TEST_DEVICE_ID
        );

        // When
        ResponseDto dto = ResponseDtoMapper.toDto(domain, TEST_MATERIAL_ID);

        // Then
        assertEquals(Boolean.TRUE, dto.getIsCorrect());
    }

    @Test
    public void testToDtoWithNullMaterialId() {
        // Given
        Response domain = new Response(
                TEST_ID,
                TEST_QUESTION_ID,
                TEST_ANSWER,
                false,
                TEST_TIMESTAMP,
                false,
                TEST_DEVICE_ID
        );

        // When
        ResponseDto dto = ResponseDtoMapper.toDto(domain, null);

        // Then
        assertNotNull(dto);
        assertNull(dto.getMaterialId());
    }

    @Test
    public void testToDtoPreservesClientGeneratedId() {
        // Per API Contract §4.1, Response IDs are generated by Android
        // and must be preserved for Windows to use
        String androidGeneratedId = "7c9e6679-7425-40de-944b-e07fc1f90ae7";
        Response domain = new Response(
                androidGeneratedId,
                TEST_QUESTION_ID,
                TEST_ANSWER,
                false,
                TEST_TIMESTAMP,
                false,
                TEST_DEVICE_ID
        );

        ResponseDto dto = ResponseDtoMapper.toDto(domain, TEST_MATERIAL_ID);

        assertEquals(androidGeneratedId, dto.getId());
    }

    @Test
    public void testToDtoList() {
        // Given
        Response response1 = new Response(
                "resp-1",
                "q-1",
                "A",
                true,
                TEST_TIMESTAMP,
                false,
                TEST_DEVICE_ID
        );
        Response response2 = new Response(
                "resp-2",
                "q-2",
                "B",
                false,
                TEST_TIMESTAMP + 1000,
                false,
                TEST_DEVICE_ID
        );
        List<Response> responses = Arrays.asList(response1, response2);

        // When
        List<ResponseDto> dtos = ResponseDtoMapper.toDtoList(responses, TEST_MATERIAL_ID);

        // Then
        assertNotNull(dtos);
        assertEquals(2, dtos.size());
        assertEquals("resp-1", dtos.get(0).getId());
        assertEquals("resp-2", dtos.get(1).getId());
        assertEquals(TEST_MATERIAL_ID, dtos.get(0).getMaterialId());
        assertEquals(TEST_MATERIAL_ID, dtos.get(1).getMaterialId());
    }

    @Test
    public void testToDtoListEmpty() {
        // Given
        List<Response> emptyList = Arrays.asList();

        // When
        List<ResponseDto> dtos = ResponseDtoMapper.toDtoList(emptyList, TEST_MATERIAL_ID);

        // Then
        assertNotNull(dtos);
        assertTrue(dtos.isEmpty());
    }

    @Test
    public void testToBatchDto() {
        // Given
        Response response1 = new Response(
                "resp-1",
                "q-1",
                "A",
                true,
                TEST_TIMESTAMP,
                false,
                TEST_DEVICE_ID
        );
        Response response2 = new Response(
                "resp-2",
                "q-2",
                "B",
                false,
                TEST_TIMESTAMP + 1000,
                false,
                TEST_DEVICE_ID
        );
        List<Response> responses = Arrays.asList(response1, response2);

        // When
        BatchResponseDto batchDto = ResponseDtoMapper.toBatchDto(responses, TEST_MATERIAL_ID);

        // Then
        assertNotNull(batchDto);
        assertNotNull(batchDto.getResponses());
        assertEquals(2, batchDto.size());
        assertFalse(batchDto.isEmpty());
    }

    @Test
    public void testToBatchDtoEmpty() {
        // Given
        List<Response> emptyList = Arrays.asList();

        // When
        BatchResponseDto batchDto = ResponseDtoMapper.toBatchDto(emptyList, TEST_MATERIAL_ID);

        // Then
        assertNotNull(batchDto);
        assertNotNull(batchDto.getResponses());
        assertEquals(0, batchDto.size());
        assertTrue(batchDto.isEmpty());
    }

    @Test
    public void testFormatTimestamp() {
        // Given - known timestamp for 2023-10-27T10:30:00Z
        long timestamp = 1698400200000L;

        // When
        String formatted = ResponseDtoMapper.formatTimestamp(timestamp);

        // Then
        assertNotNull(formatted);
        assertEquals("2023-10-27T09:50:00Z", formatted);
    }

    @Test
    public void testFormatTimestampZero() {
        // Given
        long timestamp = 0L;

        // When
        String formatted = ResponseDtoMapper.formatTimestamp(timestamp);

        // Then
        assertNotNull(formatted);
        assertEquals("1970-01-01T00:00:00Z", formatted);
    }

    @Test
    public void testFormatTimestampRecentDate() {
        // Given - a more recent date
        // 2024-01-15T14:30:00Z = 1705329000000L
        long timestamp = 1705329000000L;

        // When
        String formatted = ResponseDtoMapper.formatTimestamp(timestamp);

        // Then
        assertNotNull(formatted);
        assertEquals("2024-01-15T14:30:00Z", formatted);
    }

    @Test
    public void testParseTimestamp() {
        // Given
        String isoTimestamp = "2023-10-27T09:50:00Z";

        // When
        long timestamp = ResponseDtoMapper.parseTimestamp(isoTimestamp);

        // Then
        assertEquals(1698400200000L, timestamp);
    }

    @Test
    public void testParseTimestampNull() {
        // Given
        String isoTimestamp = null;

        // When
        long timestamp = ResponseDtoMapper.parseTimestamp(isoTimestamp);

        // Then
        assertEquals(0L, timestamp);
    }

    @Test
    public void testParseTimestampEmpty() {
        // Given
        String isoTimestamp = "";

        // When
        long timestamp = ResponseDtoMapper.parseTimestamp(isoTimestamp);

        // Then
        assertEquals(0L, timestamp);
    }

    @Test
    public void testParseTimestampInvalid() {
        // Given - invalid format
        String isoTimestamp = "not-a-timestamp";

        // When
        long timestamp = ResponseDtoMapper.parseTimestamp(isoTimestamp);

        // Then
        assertEquals(0L, timestamp);
    }

    @Test
    public void testTimestampRoundTrip() {
        // Given
        long originalTimestamp = 1698400200000L;

        // When
        String formatted = ResponseDtoMapper.formatTimestamp(originalTimestamp);
        long parsed = ResponseDtoMapper.parseTimestamp(formatted);

        // Then
        assertEquals(originalTimestamp, parsed);
    }

    @Test
    public void testToDtoTimestampFormat() {
        // Per API Contract §4.4, timestamps are transmitted as ISO 8601 strings
        Response domain = new Response(
                TEST_ID,
                TEST_QUESTION_ID,
                TEST_ANSWER,
                false,
                1698400200000L,  // 2023-10-27T09:50:00Z
                false,
                TEST_DEVICE_ID
        );

        ResponseDto dto = ResponseDtoMapper.toDto(domain, TEST_MATERIAL_ID);

        // Verify timestamp is in ISO 8601 format
        assertEquals("2023-10-27T09:50:00Z", dto.getTimestamp());
    }

    @Test
    public void testPrivateConstructorThrowsException() throws Exception {
        // Use reflection to access private constructor
        java.lang.reflect.Constructor<ResponseDtoMapper> constructor =
                ResponseDtoMapper.class.getDeclaredConstructor();
        constructor.setAccessible(true);
        try {
            constructor.newInstance();
            throw new AssertionError("Expected constructor to throw AssertionError");
        } catch (java.lang.reflect.InvocationTargetException e) {
            // Verify the cause is AssertionError
            assertEquals(AssertionError.class, e.getCause().getClass());
        }
    }

    @Test
    public void testBatchSubmissionScenario() {
        // Simulate offline mode with responses collected over time
        Response response1 = new Response(
                "offline-1",
                "q-1",
                "A",
                true,
                1698400200000L,  // 09:50
                false,
                TEST_DEVICE_ID
        );
        Response response2 = new Response(
                "offline-2",
                "q-2",
                "Written answer text here",
                false,
                1698400260000L,  // 09:51
                false,
                TEST_DEVICE_ID
        );
        Response response3 = new Response(
                "offline-3",
                "q-3",
                "42",
                true,
                1698400320000L,  // 09:52
                false,
                TEST_DEVICE_ID
        );
        List<Response> offlineResponses = Arrays.asList(response1, response2, response3);

        BatchResponseDto batch = ResponseDtoMapper.toBatchDto(offlineResponses, TEST_MATERIAL_ID);

        assertEquals(3, batch.size());

        // Verify each response has its original ID preserved
        assertEquals("offline-1", batch.getResponses().get(0).getId());
        assertEquals("offline-2", batch.getResponses().get(1).getId());
        assertEquals("offline-3", batch.getResponses().get(2).getId());

        // Verify timestamps are in ISO 8601 format
        assertEquals("2023-10-27T09:50:00Z", batch.getResponses().get(0).getTimestamp());
        assertEquals("2023-10-27T09:51:00Z", batch.getResponses().get(1).getTimestamp());
        assertEquals("2023-10-27T09:52:00Z", batch.getResponses().get(2).getTimestamp());
    }
}
