package com.manuscripta.student.network.dto;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.google.gson.annotations.SerializedName;

/**
 * Data Transfer Object for device information and metadata.
 * Per Validation Rules.md §1(6), field names use PascalCase in JSON.
 *
 * <p>Used during device pairing (API Contract §2.4) and for device identification.
 * Contains device identification and metadata for display/tracking purposes.</p>
 *
 * <p>Related requirements: Pairing Process Specification §2</p>
 */
public class DeviceInfoDto {

    /**
     * The unique identifier for the device (UUID format).
     * Generated by the Android client per Validation Rules.md §3(4).
     */
    @SerializedName("DeviceId")
    @Nullable
    private String deviceId;

    /**
     * The user-provided name for the device.
     * Used for display purposes in the teacher application.
     */
    @SerializedName("Name")
    @Nullable
    private String name;

    /**
     * Default constructor for Gson deserialization.
     */
    public DeviceInfoDto() {
    }

    /**
     * Constructor with all fields.
     *
     * @param deviceId The unique identifier for the device
     * @param name     The user-provided name for the device
     */
    public DeviceInfoDto(@Nullable String deviceId, @Nullable String name) {
        this.deviceId = deviceId;
        this.name = name;
    }

    /**
     * Gets the device identifier.
     *
     * @return The device ID
     */
    @Nullable
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * Sets the device identifier.
     *
     * @param deviceId The device ID
     */
    public void setDeviceId(@Nullable String deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * Gets the device name.
     *
     * @return The user-provided device name
     */
    @Nullable
    public String getName() {
        return name;
    }

    /**
     * Sets the device name.
     *
     * @param name The user-provided device name
     */
    public void setName(@Nullable String name) {
        this.name = name;
    }

    @Override
    @NonNull
    public String toString() {
        return "DeviceInfoDto{"
                + "deviceId='" + deviceId + '\''
                + ", name='" + name + '\''
                + '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeviceInfoDto that = (DeviceInfoDto) o;
        if (deviceId != null ? !deviceId.equals(that.deviceId) : that.deviceId != null) {
            return false;
        }
        return name != null ? name.equals(that.name) : that.name == null;
    }

    @Override
    public int hashCode() {
        int result = deviceId != null ? deviceId.hashCode() : 0;
        result = 31 * result + (name != null ? name.hashCode() : 0);
        return result;
    }
}
