package com.manuscripta.student.network.dto;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.google.gson.annotations.SerializedName;

/**
 * Data Transfer Object for device pairing request.
 * Per API Contract §2.4, used during the pairing handshake to register a student device
 * with the teacher server.
 *
 * <p>The pairing request is sent via {@code POST /pair} during the initial device setup.
 * See Pairing Process.md §2 for the full pairing sequence.</p>
 *
 * <p>Per Validation Rules §1(6), field names use PascalCase in JSON.</p>
 */
public class PairRequestDto {

    /**
     * Unique device identifier (UUID) generated by the Android client.
     * Must be preserved throughout the device lifetime.
     */
    @SerializedName("DeviceId")
    @Nullable
    private String deviceId;

    /**
     * User-friendly device name provided by the student or teacher.
     * Used for identification in the teacher's interface.
     */
    @SerializedName("name")
    @Nullable
    private String name;

    /**
     * Default constructor for Gson deserialization.
     */
    public PairRequestDto() {
    }

    /**
     * Constructor with all fields.
     *
     * @param deviceId Unique device identifier (UUID)
     * @param name     User-friendly device name
     */
    public PairRequestDto(@Nullable String deviceId, @Nullable String name) {
        this.deviceId = deviceId;
        this.name = name;
    }

    /**
     * Gets the device ID.
     *
     * @return The unique device identifier (UUID)
     */
    @Nullable
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * Sets the device ID.
     *
     * @param deviceId The unique device identifier (UUID)
     */
    public void setDeviceId(@Nullable String deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * Gets the device name.
     *
     * @return The user-friendly device name
     */
    @Nullable
    public String getName() {
        return name;
    }

    /**
     * Sets the device name.
     *
     * @param name The user-friendly device name
     */
    public void setName(@Nullable String name) {
        this.name = name;
    }

    @Override
    @NonNull
    public String toString() {
        return "PairRequestDto{"
                + "deviceId='" + deviceId + '\''
                + ", name='" + name + '\''
                + '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PairRequestDto that = (PairRequestDto) o;
        if (deviceId != null ? !deviceId.equals(that.deviceId) : that.deviceId != null) {
            return false;
        }
        return name != null ? name.equals(that.name) : that.name == null;
    }

    @Override
    public int hashCode() {
        int result = deviceId != null ? deviceId.hashCode() : 0;
        result = 31 * result + (name != null ? name.hashCode() : 0);
        return result;
    }
}
