package com.manuscripta.student.network.dto;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.google.gson.annotations.SerializedName;

/**
 * Data Transfer Object for submitting a student response to the teacher application.
 * Per API Contract §2.4 (Submit Response), this represents the request body for POST /responses.
 *
 * <p>Per API Contract §4.1 and Validation Rules §3(2)(b), Response IDs are generated by
 * the Android client and must be included in network transmission for the Windows teacher
 * application to preserve them.</p>
 *
 * <p>Per Validation Rules §1(6), field names use PascalCase in JSON.</p>
 */
public class ResponseDto {

    /**
     * Unique identifier for the response (UUID generated by Android client).
     * Per API Contract §4.1, this ID must be preserved by the Windows server.
     */
    @SerializedName("Id")
    @Nullable
    private String id;

    /**
     * The ID of the question this response answers.
     */
    @SerializedName("QuestionId")
    @Nullable
    private String questionId;

    /**
     * The ID of the material containing the question.
     */
    @SerializedName("MaterialId")
    @Nullable
    private String materialId;

    /**
     * The device ID identifying the submitter.
     * Per Validation Rules §2C(1)(d), this is the device ID the response is from.
     */
    @SerializedName("DeviceId")
    @Nullable
    private String deviceId;

    /**
     * The student's answer to the question.
     */
    @SerializedName("Answer")
    @Nullable
    private String answer;

    /**
     * Timestamp when the response was recorded (ISO 8601 format).
     */
    @SerializedName("Timestamp")
    @Nullable
    private String timestamp;

    /**
     * Optional field indicating whether the response is correct.
     * Per Validation Rules §2C(2)(a), the Android device may assist in validating simple questions.
     */
    @SerializedName("IsCorrect")
    @Nullable
    private Boolean isCorrect;

    /**
     * Default constructor for Gson deserialization.
     */
    public ResponseDto() {
    }

    /**
     * Constructor with all fields.
     *
     * @param id         Unique identifier (UUID generated by Android)
     * @param questionId The ID of the question being answered
     * @param materialId The ID of the material containing the question
     * @param deviceId   The device ID of the submitter
     * @param answer     The student's answer
     * @param timestamp  Timestamp in ISO 8601 format
     * @param isCorrect  Optional correctness indicator
     */
    public ResponseDto(@Nullable String id,
                       @Nullable String questionId,
                       @Nullable String materialId,
                       @Nullable String deviceId,
                       @Nullable String answer,
                       @Nullable String timestamp,
                       @Nullable Boolean isCorrect) {
        this.id = id;
        this.questionId = questionId;
        this.materialId = materialId;
        this.deviceId = deviceId;
        this.answer = answer;
        this.timestamp = timestamp;
        this.isCorrect = isCorrect;
    }

    /**
     * Gets the unique identifier.
     *
     * @return The response ID (UUID)
     */
    @Nullable
    public String getId() {
        return id;
    }

    /**
     * Sets the unique identifier.
     *
     * @param id The response ID (UUID)
     */
    public void setId(@Nullable String id) {
        this.id = id;
    }

    /**
     * Gets the question ID.
     *
     * @return The ID of the question being answered
     */
    @Nullable
    public String getQuestionId() {
        return questionId;
    }

    /**
     * Sets the question ID.
     *
     * @param questionId The ID of the question being answered
     */
    public void setQuestionId(@Nullable String questionId) {
        this.questionId = questionId;
    }

    /**
     * Gets the material ID.
     *
     * @return The ID of the material containing the question
     */
    @Nullable
    public String getMaterialId() {
        return materialId;
    }

    /**
     * Sets the material ID.
     *
     * @param materialId The ID of the material containing the question
     */
    public void setMaterialId(@Nullable String materialId) {
        this.materialId = materialId;
    }

    /**
     * Gets the device ID.
     *
     * @return The device ID of the submitter
     */
    @Nullable
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * Sets the device ID.
     *
     * @param deviceId The device ID of the submitter
     */
    public void setDeviceId(@Nullable String deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * Gets the answer.
     *
     * @return The student's answer
     */
    @Nullable
    public String getAnswer() {
        return answer;
    }

    /**
     * Sets the answer.
     *
     * @param answer The student's answer
     */
    public void setAnswer(@Nullable String answer) {
        this.answer = answer;
    }

    /**
     * Gets the timestamp.
     *
     * @return Timestamp in ISO 8601 format
     */
    @Nullable
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the timestamp.
     *
     * @param timestamp Timestamp in ISO 8601 format
     */
    public void setTimestamp(@Nullable String timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * Gets the correctness indicator.
     *
     * @return Whether the response is correct, or null if not evaluated
     */
    @Nullable
    public Boolean getIsCorrect() {
        return isCorrect;
    }

    /**
     * Sets the correctness indicator.
     *
     * @param isCorrect Whether the response is correct
     */
    public void setIsCorrect(@Nullable Boolean isCorrect) {
        this.isCorrect = isCorrect;
    }

    @Override
    @NonNull
    public String toString() {
        return "ResponseDto{"
                + "id='" + id + '\''
                + ", questionId='" + questionId + '\''
                + ", materialId='" + materialId + '\''
                + ", deviceId='" + deviceId + '\''
                + ", answer='" + answer + '\''
                + ", timestamp='" + timestamp + '\''
                + ", isCorrect=" + isCorrect
                + '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ResponseDto that = (ResponseDto) o;
        if (id != null ? !id.equals(that.id) : that.id != null) {
            return false;
        }
        if (questionId != null ? !questionId.equals(that.questionId) : that.questionId != null) {
            return false;
        }
        if (materialId != null ? !materialId.equals(that.materialId) : that.materialId != null) {
            return false;
        }
        if (deviceId != null ? !deviceId.equals(that.deviceId) : that.deviceId != null) {
            return false;
        }
        if (answer != null ? !answer.equals(that.answer) : that.answer != null) {
            return false;
        }
        if (timestamp != null ? !timestamp.equals(that.timestamp) : that.timestamp != null) {
            return false;
        }
        return isCorrect != null ? isCorrect.equals(that.isCorrect) : that.isCorrect == null;
    }

    @Override
    public int hashCode() {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + (questionId != null ? questionId.hashCode() : 0);
        result = 31 * result + (materialId != null ? materialId.hashCode() : 0);
        result = 31 * result + (deviceId != null ? deviceId.hashCode() : 0);
        result = 31 * result + (answer != null ? answer.hashCode() : 0);
        result = 31 * result + (timestamp != null ? timestamp.hashCode() : 0);
        result = 31 * result + (isCorrect != null ? isCorrect.hashCode() : 0);
        return result;
    }
}
