package com.manuscripta.student.data.model;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Index;
import androidx.room.PrimaryKey;

/**
 * Room entity representing teacher feedback on a student's response.
 * Feedback contains optional textual comments and/or numerical marks.
 *
 * <p>Entity IDs are generated by the Windows teacher application and preserved
 * when transmitted to the Android client.</p>
 *
 * <p>Per Validation Rules.md §2F, at least one of {@code text} or {@code marks}
 * must be non-null for valid feedback.</p>
 */
@Entity(
    tableName = "feedback",
    foreignKeys = @ForeignKey(
        entity = ResponseEntity.class,
        parentColumns = "id",
        childColumns = "responseId",
        onDelete = ForeignKey.CASCADE
    ),
    indices = @Index("responseId")
)
public class FeedbackEntity {

    /** The unique identifier for the feedback (UUID assigned by Windows). */
    @PrimaryKey
    @NonNull
    private final String id;

    /** The ID of the response this feedback is for. */
    @NonNull
    private final String responseId;

    /** Optional textual feedback from the teacher. */
    @Nullable
    private final String text;

    /** Optional numerical marks awarded. */
    @Nullable
    private final Integer marks;

    /**
     * Standard constructor used by Room to recreate objects from the database.
     *
     * @param id         The unique identifier for the feedback (UUID)
     * @param responseId The ID of the response this feedback is for
     * @param text       Optional textual feedback
     * @param marks      Optional numerical marks
     */
    public FeedbackEntity(@NonNull String id,
                          @NonNull String responseId,
                          @Nullable String text,
                          @Nullable Integer marks) {
        this.id = id;
        this.responseId = responseId;
        this.text = text;
        this.marks = marks;
    }

    /**
     * Returns the unique identifier for this feedback.
     *
     * @return The feedback ID (UUID)
     */
    @NonNull
    public String getId() {
        return id;
    }

    /**
     * Returns the ID of the response this feedback is for.
     *
     * @return The response ID (UUID)
     */
    @NonNull
    public String getResponseId() {
        return responseId;
    }

    /**
     * Returns the optional textual feedback.
     *
     * @return The text feedback, or null if not provided
     */
    @Nullable
    public String getText() {
        return text;
    }

    /**
     * Returns the optional numerical marks.
     *
     * @return The marks awarded, or null if not provided
     */
    @Nullable
    public Integer getMarks() {
        return marks;
    }
}
