package com.manuscripta.student.data.model;

import androidx.annotation.NonNull;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Ignore;
import androidx.room.Index;
import androidx.room.PrimaryKey;

import java.util.UUID;

/**
 * Room entity representing a student's response to a question.
 * Responses are linked to a parent QuestionEntity via foreign key.
 *
 * <p>Entity IDs are generated by the Android client and preserved when
 * transmitted to the Windows teacher application.</p>
 */
@Entity(
    tableName = "responses",
    foreignKeys = @ForeignKey(
        entity = QuestionEntity.class,
        parentColumns = "id",
        childColumns = "questionId",
        onDelete = ForeignKey.CASCADE
    ),
    indices = @Index("questionId")
)
public class ResponseEntity {

    @PrimaryKey
    @NonNull
    private final String id;

    @NonNull
    private String questionId;

    @NonNull
    private String selectedAnswer;

    private boolean isCorrect;

    private long timestamp;

    /**
     * Indicates whether this response has been synced to the teacher's Windows app.
     */
    private boolean synced;

    // -------------------------------------------------------------------------
    // CONSTRUCTOR 1: For Room (Rehydration)
    // -------------------------------------------------------------------------
    /**
     * Standard constructor used by Room to recreate objects from the database.
     * Pass the existing ID explicitly.
     */
    public ResponseEntity(@NonNull String id,
                          @NonNull String questionId,
                          @NonNull String selectedAnswer,
                          boolean isCorrect,
                          long timestamp,
                          boolean synced) {
        this.id = id;
        this.questionId = questionId;
        this.selectedAnswer = selectedAnswer;
        this.isCorrect = isCorrect;
        this.timestamp = timestamp;
        this.synced = synced;
    }

    // -------------------------------------------------------------------------
    // CONSTRUCTOR 2: For the App (Creation)
    // -------------------------------------------------------------------------
    /**
     * Convenience constructor for creating NEW responses.
     * Automatically generates a random UUID and sets default values.
     * Annotated with @Ignore so Room doesn't try to use it.
     */
    @Ignore
    public ResponseEntity(@NonNull String questionId, @NonNull String selectedAnswer) {
        this(
            UUID.randomUUID().toString(),
            questionId,
            selectedAnswer,
            false,
            System.currentTimeMillis(),
            false
        );
    }

    // Getters and Setters

    @NonNull
    public String getId() {
        return id;
    }

    @NonNull
    public String getQuestionId() {
        return questionId;
    }

    public void setQuestionId(@NonNull String questionId) {
        this.questionId = questionId;
    }

    @NonNull
    public String getSelectedAnswer() {
        return selectedAnswer;
    }

    public void setSelectedAnswer(@NonNull String selectedAnswer) {
        this.selectedAnswer = selectedAnswer;
    }

    public boolean isCorrect() {
        return isCorrect;
    }

    public void setCorrect(boolean correct) {
        isCorrect = correct;
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    public boolean isSynced() {
        return synced;
    }

    public void setSynced(boolean synced) {
        this.synced = synced;
    }
}
