package com.manuscripta.student.data.model;

import androidx.annotation.NonNull;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Index;
import androidx.room.PrimaryKey;

/**
 * Room entity representing a student's response to a question.
 * Responses are linked to a parent QuestionEntity via foreign key.
 *
 * <p>Entity IDs are generated by the Android client and preserved when
 * transmitted to the Windows teacher application.</p>
 */
@Entity(
    tableName = "responses",
    foreignKeys = @ForeignKey(
        entity = QuestionEntity.class,
        parentColumns = "id",
        childColumns = "questionId",
        onDelete = ForeignKey.CASCADE
    ),
    indices = @Index("questionId")
)
public class ResponseEntity {

    /** The unique identifier for the response. */
    @PrimaryKey
    @NonNull
    private final String id;

    /** The ID of the question this response is for. */
    @NonNull
    private String questionId;

    /** The answer selected by the student. */
    @NonNull
    private String selectedAnswer;

    /** Whether the response is correct. */
    private boolean isCorrect;

    /** The timestamp when the response was recorded (Unix epoch milliseconds). */
    private long timestamp;

    /** Indicates whether this response has been synced to the teacher's Windows app. */
    private boolean synced;

    /** The device identifier for the tablet that submitted this response. */
    @NonNull
    private final String deviceId;

    /**
     * Standard constructor used by Room to recreate objects from the database.
     * Pass the existing ID explicitly.
     *
     * @param id             The unique identifier for the response
     * @param questionId     The ID of the question this response is for
     * @param selectedAnswer The answer selected by the student
     * @param isCorrect      Whether the response is correct
     * @param timestamp      The timestamp when the response was recorded
     * @param synced         Whether the response has been synced
     * @param deviceId       The device identifier for the tablet that submitted this response
     */
    public ResponseEntity(@NonNull String id,
                          @NonNull String questionId,
                          @NonNull String selectedAnswer,
                          boolean isCorrect,
                          long timestamp,
                          boolean synced,
                          @NonNull String deviceId) {
        this.id = id;
        this.questionId = questionId;
        this.selectedAnswer = selectedAnswer;
        this.isCorrect = isCorrect;
        this.timestamp = timestamp;
        this.synced = synced;
        this.deviceId = deviceId;
    }

    // Getters

    @NonNull
    public String getId() {
        return id;
    }

    @NonNull
    public String getQuestionId() {
        return questionId;
    }

    @NonNull
    public String getSelectedAnswer() {
        return selectedAnswer;
    }

    public boolean isCorrect() {
        return isCorrect;
    }

    public long getTimestamp() {
        return timestamp;
    }

    public boolean isSynced() {
        return synced;
    }

    @NonNull
    public String getDeviceId() {
        return deviceId;
    }
}
