package com.manuscripta.student.data.model;

import androidx.annotation.NonNull;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Index;
import androidx.room.PrimaryKey;

/**
 * Room entity representing a learning session.
 * Sessions track when a student is working on a material.
 *
 * <p>Entity IDs are generated by the Android client and preserved when
 * transmitted to the Windows teacher application.</p>
 */
@Entity(
    tableName = "sessions",
    foreignKeys = @ForeignKey(
        entity = MaterialEntity.class,
        parentColumns = "id",
        childColumns = "materialId",
        onDelete = ForeignKey.CASCADE
    ),
    indices = @Index("materialId")
)
public class SessionEntity {

    @PrimaryKey
    @NonNull
    private final String id;

    @NonNull
    private String materialId;

    private long startTime;

    private long endTime;

    @NonNull
    private SessionStatus status;

    @NonNull
    private String deviceId;

    /**
     * Standard constructor used by Room to recreate objects from the database.
     * Pass the existing ID explicitly.
     */
    public SessionEntity(@NonNull String id,
                         @NonNull String materialId,
                         long startTime,
                         long endTime,
                         @NonNull SessionStatus status,
                         @NonNull String deviceId) {
        this.id = id;
        this.materialId = materialId;
        this.startTime = startTime;
        this.endTime = endTime;
        this.status = status;
        this.deviceId = deviceId;
    }

    // Getters

    @NonNull
    public String getId() {
        return id;
    }

    @NonNull
    public String getMaterialId() {
        return materialId;
    }

    public long getStartTime() {
        return startTime;
    }

    public long getEndTime() {
        return endTime;
    }

    @NonNull
    public SessionStatus getStatus() {
        return status;
    }

    @NonNull
    public String getDeviceId() {
        return deviceId;
    }
}
