package com.manuscripta.student.data.model;

import androidx.annotation.NonNull;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Index;
import androidx.room.PrimaryKey;
import androidx.room.Ignore;

import java.util.UUID;

/**
 * Room entity representing a learning session.
 * Sessions track when a student is working on a material.
 *
 * <p>Entity IDs are generated by the Android client and preserved when
 * transmitted to the Windows teacher application.</p>
 */
@Entity(
    tableName = "sessions",
    foreignKeys = @ForeignKey(
        entity = MaterialEntity.class,
        parentColumns = "id",
        childColumns = "materialId",
        onDelete = ForeignKey.CASCADE
    ),
    indices = @Index("materialId")
)
public class SessionEntity {

    @PrimaryKey
    @NonNull
    private final String id;

    @NonNull
    private String materialId;

    private long startTime;

    private long endTime;

    @NonNull
    private SessionStatus status;

    @NonNull
    private String deviceId;

    // -------------------------------------------------------------------------
    // CONSTRUCTOR 1: For Room (Rehydration)
    // -------------------------------------------------------------------------
    /**
     * Standard constructor used by Room to recreate objects from the database.
     * Pass the existing ID explicitly.
     */
    public SessionEntity(@NonNull String id,
                         @NonNull String materialId,
                         long startTime,
                         long endTime,
                         @NonNull SessionStatus status,
                         @NonNull String deviceId) {
        this.id = id;
        this.materialId = materialId;
        this.startTime = startTime;
        this.endTime = endTime;
        this.status = status;
        this.deviceId = deviceId;
    }

    // -------------------------------------------------------------------------
    // CONSTRUCTOR 2: For the App (Creation)
    // -------------------------------------------------------------------------
    /**
     * Convenience constructor for creating NEW sessions.
     * Automatically generates a random UUID and sets default values.
     * Annotated with @Ignore so Room doesn't try to use it.
     */
    @Ignore
    public SessionEntity(@NonNull String materialId, @NonNull String deviceId) {
        this.id = UUID.randomUUID().toString();
        this.materialId = materialId;
        this.startTime = System.currentTimeMillis();
        this.endTime = 0;
        this.status = SessionStatus.ACTIVE;
        this.deviceId = deviceId;
    }

    // Getters and Setters

    @NonNull
    public String getId() {
        return id;
    }

    @NonNull
    public String getMaterialId() {
        return materialId;
    }

    public void setMaterialId(@NonNull String materialId) {
        this.materialId = materialId;
    }

    public long getStartTime() {
        return startTime;
    }

    public void setStartTime(long startTime) {
        this.startTime = startTime;
    }

    public long getEndTime() {
        return endTime;
    }

    public void setEndTime(long endTime) {
        this.endTime = endTime;
    }

    @NonNull
    public SessionStatus getStatus() {
        return status;
    }

    public void setStatus(@NonNull SessionStatus status) {
        this.status = status;
    }

    @NonNull
    public String getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(@NonNull String deviceId) {
        this.deviceId = deviceId;
    }
}
