package com.manuscripta.student.data.model;

import androidx.annotation.NonNull;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Index;
import androidx.room.PrimaryKey;

/**
 * Room entity representing a learning session.
 * Sessions track when a student is working on a material.
 *
 * <p>Entity IDs are generated by the Android client and preserved when
 * transmitted to the Windows teacher application.</p>
 */
@Entity(
    tableName = "sessions",
    foreignKeys = @ForeignKey(
        entity = MaterialEntity.class,
        parentColumns = "id",
        childColumns = "materialId",
        onDelete = ForeignKey.CASCADE
    ),
    indices = @Index("materialId")
)
public class SessionEntity {

    @PrimaryKey
    @NonNull
    private String id;

    @NonNull
    private String materialId;

    private long startTime;

    private long endTime;

    @NonNull
    private SessionStatus status;

    @NonNull
    private String deviceId;

    // Default constructor
    public SessionEntity() {
        this.id = "";
        this.materialId = "";
        this.startTime = System.currentTimeMillis();
        this.endTime = 0;
        this.status = SessionStatus.ACTIVE;
        this.deviceId = "";
    }

    // Getters and Setters

    @NonNull
    public String getId() {
        return id;
    }

    public void setId(@NonNull String id) {
        this.id = id;
    }

    @NonNull
    public String getMaterialId() {
        return materialId;
    }

    public void setMaterialId(@NonNull String materialId) {
        this.materialId = materialId;
    }

    public long getStartTime() {
        return startTime;
    }

    public void setStartTime(long startTime) {
        this.startTime = startTime;
    }

    public long getEndTime() {
        return endTime;
    }

    public void setEndTime(long endTime) {
        this.endTime = endTime;
    }

    @NonNull
    public SessionStatus getStatus() {
        return status;
    }

    public void setStatus(@NonNull SessionStatus status) {
        this.status = status;
    }

    @NonNull
    public String getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(@NonNull String deviceId) {
        this.deviceId = deviceId;
    }
}
