using System.ComponentModel.DataAnnotations;

namespace Main.Models.Entities;

/// <summary>
/// Represents a paired Android device.
/// See Pairing Process.md §1(1)(a) - "The Windows device has recorded the Android device's deviceId."
/// </summary>
public class PairedDeviceEntity
{
    /// <summary>
    /// The unique identifier of the paired device.
    /// This is generated by the Android client and sent during pairing.
    /// </summary>
    [Key]
    public Guid DeviceId { get; set; }

    /// <summary>
    /// The user-friendly name of the device, provided during pairing.
    /// Per Pairing Process Specification s2(2)(c).
    /// </summary>
    [Required]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Creates a new PairedDeviceEntity.
    /// </summary>
    public PairedDeviceEntity()
    {
    }

    /// <summary>
    /// Creates a new PairedDeviceEntity with the specified device ID and name.
    /// </summary>
    /// <param name="deviceId">The device's unique identifier.</param>
    /// <param name="name">The user-friendly device name.</param>
    public PairedDeviceEntity(Guid deviceId, string name)
    {
        DeviceId = deviceId;
        Name = name ?? throw new ArgumentNullException(nameof(name));
    }
}
