using System.ComponentModel.DataAnnotations;

namespace Main.Models.Entities;

/// <summary>
/// Represents a paired reMarkable device.
/// Per AdditionalValidationRules §3D.
/// </summary>
public class ReMarkableDeviceEntity
{
    /// <summary>
    /// The unique identifier of the reMarkable device.
    /// Generated by the application during pairing.
    /// </summary>
    [Key]
    public Guid DeviceId { get; set; }

    /// <summary>
    /// The user-friendly name of the device, provided during pairing.
    /// Per RemarkableIntegrationSpecification §3(2)(a).
    /// </summary>
    [Required]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Creates a new ReMarkableDeviceEntity.
    /// </summary>
    public ReMarkableDeviceEntity()
    {
    }

    /// <summary>
    /// Creates a new ReMarkableDeviceEntity with the specified device ID and name.
    /// </summary>
    /// <param name="deviceId">The device's unique identifier.</param>
    /// <param name="name">The user-friendly device name.</param>
    public ReMarkableDeviceEntity(Guid deviceId, string name)
    {
        DeviceId = deviceId;
        Name = name ?? throw new ArgumentNullException(nameof(name));
    }
}
