using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using Main.Models.Enums;

namespace Main.Models.Entities;

/// <summary>
/// Data entity for persisting sessions to the database.
/// Represents a student's session working on a specific material.
/// Validation rules defined in Validation Rules §2D.
/// </summary>
[Table("Sessions")]
public class SessionDataEntity
{
    /// <summary>
    /// Unique identifier for the session (generated by Android client per §3(2)).
    /// </summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public Guid Id { get; private set; }

    /// <summary>
    /// References the material the student should work on during the lesson.
    /// §2D(1)(a)
    /// </summary>
    [Required]
    public Guid MaterialId { get; private set; }

    /// <summary>
    /// Start timestamp of the session.
    /// §2D(1)(b)
    /// </summary>
    [Required]
    public DateTime StartTime { get; private set; }

    /// <summary>
    /// Session status indicating current state.
    /// §2D(1)(c)
    /// </summary>
    [Required]
    public SessionStatus SessionStatus { get; private set; }

    /// <summary>
    /// The device ID the session is related to.
    /// §2D(1)(d)
    /// </summary>
    [Required]
    public Guid DeviceId { get; private set; }

    /// <summary>
    /// End timestamp, for non-active sessions.
    /// §2D(2)(a) - Optional, but required when SessionStatus is PAUSED, COMPLETED, or CANCELLED per §2D(3)(a).
    /// </summary>
    public DateTime? EndTime { get; private set; }

    // Foreign key navigation (internal: available to services/repositories within assembly)
    [ForeignKey("MaterialId")]
    internal MaterialDataEntity? Material { get; private set; }

    /// <summary>
    /// Private parameterless constructor for EF Core.
    /// </summary>
    private SessionDataEntity() { }

    /// <summary>
    /// Creates a new SessionDataEntity.
    /// </summary>
    /// <param name="id">Unique session ID (generated by Android client).</param>
    /// <param name="materialId">The material this session is associated with.</param>
    /// <param name="startTime">Timestamp of session start.</param>
    /// <param name="sessionStatus">Current session status.</param>
    /// <param name="deviceId">The device ID this session belongs to.</param>
    /// <param name="endTime">Optional end time (required for non-ACTIVE sessions).</param>
    /// <exception cref="ArgumentException">
    /// Thrown when a non-ACTIVE session is created without an EndTime (per §2D(3)(a)).
    /// </exception>
    public SessionDataEntity(
        Guid id,
        Guid materialId,
        DateTime startTime,
        SessionStatus sessionStatus,
        Guid deviceId,
        DateTime? endTime = null)
    {
        // Validate §2D(3)(a): Non-active sessions must have EndTime
        if (sessionStatus != SessionStatus.ACTIVE && !endTime.HasValue)
        {
            throw new ArgumentException(
                $"Sessions with status {sessionStatus} must have an EndTime (Validation Rules §2D(3)(a)).",
                nameof(endTime));
        }

        // TODO: Validate §2D(3)(b): DeviceId must correspond to a valid device
        // This requires DeviceIdValidator.IsValidDeviceId(deviceId) once device registration is implemented

        Id = id;
        MaterialId = materialId;
        StartTime = startTime;
        SessionStatus = sessionStatus;
        DeviceId = deviceId;
        EndTime = endTime;
    }
}
