package com.manuscripta.student.integration.http;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import com.manuscripta.student.integration.IntegrationTest;
import com.manuscripta.student.integration.config.IntegrationTestConfig;
import com.manuscripta.student.integration.harness.NetworkIntegrationHarness;
import com.manuscripta.student.network.dto.BatchResponseDto;
import com.manuscripta.student.network.dto.DeviceInfoDto;
import com.manuscripta.student.network.dto.ResponseDto;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.experimental.categories.Category;
import org.junit.runner.RunWith;
import org.robolectric.RobolectricTestRunner;
import org.robolectric.annotation.Config;

import java.time.Instant;
import java.util.Arrays;
import java.util.UUID;

import retrofit2.Response;

/**
 * Integration tests for {@code POST /responses} and
 * {@code POST /responses/batch} endpoints.
 *
 * <p>Per API Contract §2.4, submitting a valid response returns 201
 * Created. The response ID is generated by the Android client and
 * preserved by the server.</p>
 */
@RunWith(RobolectricTestRunner.class)
@Config(sdk = 28, manifest = Config.NONE)
@Category(IntegrationTest.class)
public class ResponseSubmissionIntegrationTest {

    private NetworkIntegrationHarness harness;

    /** Wires harness and pairs the test device. */
    @Before
    public void setUp() throws Exception {
        harness = new NetworkIntegrationHarness(
                IntegrationTestConfig.fromEnvironment());
        harness.setUp();

        DeviceInfoDto info = new DeviceInfoDto(
                harness.getConfig().getTestDeviceId(),
                harness.getConfig().getTestDeviceName());
        harness.getApiService().registerDevice(info).execute();
    }

    /** Disconnects TCP and releases resources. */
    @After
    public void tearDown() {
        harness.tearDown();
    }

    /**
     * Verifies that submitting a single valid response returns 201.
     *
     * @throws Exception if the network call fails unexpectedly
     */
    @Test
    public void submitResponse_validPayload_returns201()
            throws Exception {
        ResponseDto dto = buildTestResponse();

        Response<Void> response = harness.getApiService()
                .submitResponse(dto).execute();

        assertEquals(201, response.code());
    }

    /**
     * Verifies that submitting a malformed response (missing required
     * fields) returns a client-error status.
     *
     * @throws Exception if the network call fails unexpectedly
     */
    @Test
    public void submitResponse_malformed_returnsClientError()
            throws Exception {
        ResponseDto dto = new ResponseDto();
        // All fields null — should fail validation

        Response<Void> response = harness.getApiService()
                .submitResponse(dto).execute();

        assertNotNull(response);
        int code = response.code();
        assertTrue("Expected 4xx for malformed response",
                code >= 400 && code < 500);
    }

    /**
     * Verifies that batch-submitting valid responses returns 201.
     *
     * @throws Exception if the network call fails unexpectedly
     */
    @Test
    public void submitBatchResponses_validPayload_returns201()
            throws Exception {
        BatchResponseDto batch = new BatchResponseDto(
                Arrays.asList(buildTestResponse(),
                        buildTestResponse()));

        Response<Void> response = harness.getApiService()
                .submitBatchResponses(batch).execute();

        assertEquals(201, response.code());
    }

    /**
     * Verifies that a batch containing a malformed response is
     * rejected entirely. Per API Contract §4.7, all-or-nothing
     * semantics apply: if any response is invalid the whole batch
     * must return a client-error status.
     *
     * @throws Exception if the network call fails unexpectedly
     */
    @Test
    public void submitBatchResponses_malformed_returnsClientError()
            throws Exception {
        ResponseDto valid = buildTestResponse();
        ResponseDto malformed = new ResponseDto();
        // One valid + one all-null — batch should be rejected

        BatchResponseDto batch = new BatchResponseDto(
                Arrays.asList(valid, malformed));

        Response<Void> response = harness.getApiService()
                .submitBatchResponses(batch).execute();

        assertNotNull(response);
        int code = response.code();
        assertTrue("Expected 4xx for batch with malformed entry",
                code >= 400 && code < 500);
    }

    // ---------------------------------------------------------------
    // Helpers
    // ---------------------------------------------------------------

    private ResponseDto buildTestResponse() {
        return new ResponseDto(
                UUID.randomUUID().toString(),
                "00000001-0000-0000-0000-000000000002",
                "00000001-0000-0000-0000-000000000003",
                harness.getConfig().getTestDeviceId(),
                "Sample answer",
                Instant.now().toString(),
                null);
    }
}
