plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.ksp)
    alias(libs.plugins.hilt)
    id("checkstyle")
    id("jacoco")
}

android {
    namespace = "com.manuscripta.student"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.manuscripta.student"
        minSdk = 27
        targetSdk = 36
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
        debug {
            enableUnitTestCoverage = true
        }
    }

    buildFeatures {
        viewBinding = true
    }

    testOptions {
        unitTests {
            isIncludeAndroidResources = true
            isReturnDefaultValues = true
        }
    }
}

kotlin {
    jvmToolchain(17)
}

dependencies {
    // AndroidX
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.material)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.lifecycle.viewmodel)
    implementation(libs.androidx.lifecycle.livedata)

    // Room
    implementation(libs.androidx.room.runtime)
    ksp(libs.androidx.room.compiler)

    // Retrofit & OkHttp
    implementation(libs.retrofit)
    implementation(libs.retrofit.gson)
    implementation(libs.okhttp.logging)

    // Hilt
    implementation(libs.hilt.android)
    ksp(libs.hilt.compiler)

    // Testing
    testImplementation(libs.junit)
    testImplementation(libs.mockito.core)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.arch.core.testing)
    testImplementation("androidx.test:core:1.6.1")
    testImplementation("com.google.dagger:hilt-android-testing:2.52")
    kspTest("com.google.dagger:hilt-android-compiler:2.52")

    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
}

// Checkstyle configuration
checkstyle {
    toolVersion = "10.12.0"
    configFile = file("${project.rootDir}/config/checkstyle/checkstyle.xml")
}

tasks.register<Checkstyle>("checkstyle") {
    source = fileTree("src/main/java")
    include("**/*.java")
    classpath = files()
}

// JaCoCo configuration
jacoco {
    toolVersion = "0.8.12"
}

tasks.register<JacocoReport>("jacocoTestReport") {
    dependsOn("testDebugUnitTest")

    reports {
        xml.required.set(true)
        html.required.set(true)
    }

    // Comprehensive filter for generated and framework code
    val fileFilter = listOf(
        // Android framework
        "**/R.class",
        "**/R\$*.class",
        "**/BuildConfig.*",
        "**/Manifest*.*",

        // Test files
        "**/*Test*.*",
        "**/*Robolectric*.*",

        // Android internals
        "android/**/*.*",

        // Data binding
        "**/databinding/*",
        "**/BR.class",

        // Generated code (general)
        "**/generated/**",

        // Hilt/Dagger generated code (most important!)
        "**/Hilt_*.*",
        "**/*_Hilt_*.*",
        "**/Dagger*.class",
        "**/*HiltComponents*.class",
        "**/*HiltModules*.class",

        // Dagger factory & injection
        "**/*_Factory*.class",
        "**/*_MembersInjector*.class",
        "**/*InstanceHolder*.class",

        // Dagger modules
        "**/*Module*.class",
        "**/*Binds*.class",
        "**/*Provides*.class",

        // Dagger component/scope related
        "**/*Component*.class",
        "**/*Scope*.class",

        // Hilt internal packages
        "dagger/hilt/internal/**",
        "dagger/hilt/android/internal/**",
        "hilt_aggregated_deps/**",

        // Application class (just framework setup)
        "**/ManuscriptaApplication.class",

        // Database implementation (generated by Room)
        "**/*_Impl*.class",
        "**/*_Impl\$*.class",

        // Room migration
        "**/*Migration*.class"
    )

    val debugTree = fileTree("${buildDir}/intermediates/javac/debug") {
        exclude(fileFilter)
    }

    val mainSrc = "${project.projectDir}/src/main/java"

    sourceDirectories.setFrom(files(mainSrc))
    classDirectories.setFrom(files(debugTree))
    executionData.setFrom(fileTree(buildDir) {
        include("**/*.exec", "**/*.ec")
    })
}

tasks.register<JacocoCoverageVerification>("jacocoTestCoverageVerification") {
    dependsOn("jacocoTestReport")

    violationRules {
        // For early-stage projects, keep this realistic
        rule {
            element = "BUNDLE"
            limit {
                minimum = "0.30".toBigDecimal()  // 30% overall - reasonable for initial structure
            }
        }

        // Stricter requirements for core classes
        rule {
            element = "CLASS"
            includes = listOf(
                "com.manuscripta.student.ui.main.*",
                "com.manuscripta.student.data.model.*"
            )
            limit {
                minimum = "0.70".toBigDecimal()  // 70% for UI/models
            }
        }
    }

    val fileFilter = listOf(
        // Android framework
        "**/R.class",
        "**/R\$*.class",
        "**/BuildConfig.*",
        "**/Manifest*.*",

        // Test files
        "**/*Test*.*",

        // Android internals
        "android/**/*.*",

        // Data binding
        "**/databinding/*",
        "**/BR.class",

        // Generated code
        "**/generated/**",

        // Hilt/Dagger generated (KEY!)
        "**/Hilt_*.*",
        "**/*_Hilt_*.*",
        "**/Dagger*.class",
        "**/*HiltComponents*.class",
        "**/*HiltModules*.class",
        "**/*_Factory*.class",
        "**/*_MembersInjector*.class",
        "**/*InstanceHolder*.class",
        "**/*Module*.class",
        "**/*Component*.class",
        "dagger/hilt/internal/**",
        "dagger/hilt/android/internal/**",
        "hilt_aggregated_deps/**",

        // Application class
        "**/ManuscriptaApplication.class",

        // Room generated
        "**/*_Impl*.class"
    )

    val debugTree = fileTree("${buildDir}/intermediates/javac/debug") {
        exclude(fileFilter)
    }

    val mainSrc = "${project.projectDir}/src/main/java"

    sourceDirectories.setFrom(files(mainSrc))
    classDirectories.setFrom(files(debugTree))
    executionData.setFrom(fileTree(buildDir) {
        include("**/*.exec", "**/*.ec")
    })
}