using System.ComponentModel.DataAnnotations;

namespace Main.Models.Dtos;

/// <summary>
/// Request DTO for device pairing.
/// See API Contract.md §2.4 - Device Pairing endpoint.
/// </summary>
public class PairRequest
{
    /// <summary>
    /// The unique identifier of the device requesting pairing.
    /// Generated by the Android client.
    /// </summary>
    [Required]
    public string DeviceId { get; set; } = string.Empty;
}
