using System.ComponentModel.DataAnnotations;

namespace Main.Models.Dtos;

/// <summary>
/// Request DTO for submitting a single response.
/// Per API Contract §2.3 and Validation Rules §2C.
/// </summary>
public class ResponseRequest
{
    /// <summary>
    /// Unique identifier for the response (UUID).
    /// Per Validation Rules §3(2)(b), generated by Android client.
    /// </summary>
    [Required]
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// The question this response is for (UUID).
    /// Per Validation Rules §2C(1)(a).
    /// </summary>
    [Required]
    public string QuestionId { get; set; } = string.Empty;

    /// <summary>
    /// The material ID (informational, per API Contract §2.3).
    /// </summary>
    public string? MaterialId { get; set; }

    /// <summary>
    /// The device ID the response is from.
    /// Per Validation Rules §2C(1)(d).
    /// </summary>
    [Required]
    public string DeviceId { get; set; } = string.Empty;

    /// <summary>
    /// The answer provided by the student.
    /// Type interpretation depends on question type:
    /// - MULTIPLE_CHOICE: integer index as string
    /// - WRITTEN_ANSWER: string content
    /// Per Validation Rules §2C(1)(b).
    /// </summary>
    [Required]
    public string Answer { get; set; } = string.Empty;

    /// <summary>
    /// Timestamp of response submission (ISO 8601).
    /// Per Validation Rules §2C(1)(c).
    /// </summary>
    [Required]
    public string Timestamp { get; set; } = string.Empty;

    /// <summary>
    /// Optional correctness evaluation by Android client.
    /// Per Validation Rules §2C(2)(a).
    /// </summary>
    public bool? IsCorrect { get; set; }
}
