namespace Main.Models.Dtos;

/// <summary>
/// DTO for response submission from Android client.
/// Per Validation Rules §2C (takes precedence over API Contract per §1(5)).
/// </summary>
public class SubmitResponseDto
{
    /// <summary>§2C: UUID generated by Android client per §3(2)(b).</summary>
    public required string Id { get; set; }

    /// <summary>§2C(1)(a): UUID of the question this response is for.</summary>
    public required string QuestionId { get; set; }

    /// <summary>§2C(1)(d): UUID of the device submitting the response.</summary>
    public required string DeviceId { get; set; }

    /// <summary>
    /// §2C(1)(b): The answer value (generic typing).
    /// For multiple choice, this is the index as a string.
    /// For written answers, this is the text answer.
    /// </summary>
    public required string Answer { get; set; }

    /// <summary>§2C(1)(c): ISO 8601 timestamp string.</summary>
    public required string Timestamp { get; set; }

    /// <summary>§2C(2)(a): Optional. Android device may pre-evaluate correctness.</summary>
    public bool? IsCorrect { get; set; }
}

/// <summary>
/// DTO for batch response submission.
/// Per API Contract.md §2.3.
/// </summary>
public class BatchSubmitResponsesDto
{
    public required List<SubmitResponseDto> Responses { get; set; }
}

